<a href="https://colab.research.google.com/github/itsmuza/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
mydataset = {
    'cars': ["BMW", "Volvo", "Ford"],
    'passings': [3, 7, 2]
}

df = pd.DataFrame(mydataset)

print(df)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2

In [ ]:
df.head()

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2

In [ ]:
df.tail()

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2

In [ ]:
df.shape

(3, 2)

In [ ]:
df.columns

Index(['cars', 'passings'], dtype='object')

In [ ]:
df.dtypes

cars        object
passings     int64
dtype: object

In [ ]:
df.describe()

       passings
count  3.000000
mean   4.000000
std    2.645751
min    2.000000
25%    2.500000
50%    3.000000
75%    5.000000
max    7.000000

In [ ]:
df

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2

In [ ]:
df.loc[0,"cars"]

'BMW'

In [ ]:
df[df['passings'] > 2]

    cars  passings
0    BMW         3
1  Volvo         7

In [ ]:
df.mean(numeric_only=True)

passings    4.0
dtype: float64

In [ ]:
df['passings'].mean()

np.float64(4.0)

In [ ]:
data_with_missing = {
    'cars': ["BMW", "Volvo", "Ford", "Tesla", None],
    'passings': [3, 7, 2, None, 4]
}

df_data = pd.DataFrame(data_with_missing)

print(df_data)

    cars  passings
0    BMW       3.0
1  Volvo       7.0
2   Ford       2.0
3  Tesla       NaN
4   None       4.0

In [ ]:
df_data.isnull()

    cars  passings
0  False     False
1  False     False
2  False     False
3  False      True
4   True     False

In [ ]:
df_data.dropna()

    cars  passings
0    BMW       3.0
1  Volvo       7.0
2   Ford       2.0

In [ ]:
df_data.dropna(axis=0)

    cars  passings
0    BMW       3.0
1  Volvo       7.0
2   Ford       2.0

In [ ]:
df_data

    cars  passings
0    BMW       3.0
1  Volvo       7.0
2   Ford       2.0
3  Tesla       NaN
4   None       4.0

In [ ]:
df_data.dropna(subset=['cars'])

    cars  passings
0    BMW       3.0
1  Volvo       7.0
2   Ford       2.0
3  Tesla       NaN

In [ ]:
df_data.fillna(0)

    cars  passings
0    BMW       3.0
1  Volvo       7.0
2   Ford       2.0
3  Tesla       0.0
4      0       4.0

In [ ]:
df_data.fillna({'cars': "car_name", "passings": 1})

       cars  passings
0       BMW       3.0
1     Volvo       7.0
2      Ford       2.0
3     Tesla       1.0
4  car_name       4.0

In [ ]:
# Series => 1D

a = ["bwm", "tesla", "toyota"]

myvar = pd.Series(a)

print(myvar)

0       bwm
1     tesla
2    toyota
dtype: object